name: Create Tag/Release
on:
  push:
    branches:
      - dev-deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: dev-release
      - name: Bump last released version
        run: |
          echo "release_proj_version=`poetry version -s`" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: dev-deploy
      - name: Bump version
        run: |
          echo "proj_version=`poetry version -s`" >> $GITHUB_ENV
      - name: Match versioning
        if: ${{ env.release_proj_version == env.proj_version }}
        run: |
          echo "The last released version is the same as the new one, please update the version on project.py"
          exit 1
      - name: Run squash
        run: |
          git config --local user.name $GITHUB_USERNAME
          git config --local user.email $GITHUB_EMAIL
          mkdir ./temp
          mv .git/ ./temp/
          cd ./temp
          git checkout dev-release
          mv .git/ ..
          cd ..
          rm -rf temp
          git add .
          git commit -am "update version ${{ env.proj_version }}"
        env:
          GITHUB_USERNAME: github-actions[bot]
          GITHUB_EMAIL: github-actions[bot]@users.noreply.github.com
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev-release
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          repository: OriGenAI/proteus-runtime-public
          branch: "dev"
